import React, { useState } from 'react';
import { FileText, Upload, Loader, Copy, Download } from 'lucide-react';

const FicheProduit = () => {
  const [productData, setProductData] = useState({
    name: '',
    brand: '',
    category: '',
    condition: '',
    description: '',
    price: ''
  });
  const [generatedSheet, setGeneratedSheet] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const generateSheet = () => {
    if (!productData.name || !productData.brand) return;
    
    setIsGenerating(true);
    
    setTimeout(() => {
      const sheet = `📋 FICHE PRODUIT SELEZIONE

🏷️ IDENTIFICATION
• Nom: ${productData.name}
• Marque: ${productData.brand}
• Catégorie: ${productData.category}
• État: ${productData.condition}

💰 VALORISATION
• Prix de vente: ${productData.price}€
• Estimation marché: ${Math.round(parseInt(productData.price || 0) * 0.85)}€ - ${Math.round(parseInt(productData.price || 0) * 1.15)}€
• Dépréciation moyenne: -15% / -35%

📝 DESCRIPTION OPTIMISÉE SEO
${productData.description}

Authentique ${productData.brand} ${productData.name} en ${productData.condition} état. 
Pièce d'exception de la maison ${productData.brand}, reconnue pour son savoir-faire artisanal.
Investissement de choix pour collectionneurs avisés.

🔍 MOTS-CLÉS SEO
${productData.brand}, ${productData.name}, luxe, authentique, collection, ${productData.condition}, investissement

✅ CERTIFICATIONS
• Authentification SELEZIONE: VALIDÉE
• Traçabilité: CONFIRMÉE  
• Grade qualité: PREMIUM

📊 DONNÉES MARCHÉ
• Tendance: ↗️ CROISSANTE
• Liquidité: EXCELLENTE
• Demande: FORTE

Generated by SELEZIONE IA © 2025`;

      setGeneratedSheet(sheet);
      setIsGenerating(false);
    }, 2000);
  };

  return (
    <div className="p-4 md:p-6 space-y-6">
      <div className="bg-gradient-to-r from-blue-500/10 via-indigo-500/10 to-purple-500/10 rounded-2xl p-6 border border-blue-500/20">
        <h2 className="text-2xl md:text-3xl font-bold bg-gradient-to-r from-blue-400 via-indigo-400 to-purple-400 bg-clip-text text-transparent mb-2">
          📋 GÉNÉRATEUR FICHE PRODUIT
        </h2>
        <p className="text-gray-400">Création automatique de fiches produits optimisées</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Formulaire de saisie */}
        <div className="bg-black/60 backdrop-blur-sm rounded-xl border border-blue-500/30 p-6">
          <h3 className="text-blue-400 font-bold text-lg mb-4">📝 Informations Produit</h3>
          
          <div className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <input
                type="text"
                placeholder="Nom du produit"
                value={productData.name}
                onChange={(e) => setProductData({...productData, name: e.target.value})}
                className="bg-gray-900 border border-gray-700 rounded-xl px-4 py-3 text-white placeholder-gray-400 text-sm"
              />
              <select
                value={productData.brand}
                onChange={(e) => setProductData({...productData, brand: e.target.value})}
                className="bg-gray-900 border border-gray-700 rounded-xl px-4 py-3 text-white text-sm"
              >
                <option value="">Sélectionner marque</option>
                <option value="Chanel">Chanel</option>
                <option value="Hermès">Hermès</option>
                <option value="Louis Vuitton">Louis Vuitton</option>
                <option value="Dior">Dior</option>
                <option value="Saint Laurent">Saint Laurent</option>
                <option value="Gucci">Gucci</option>
              </select>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <select
                value={productData.category}
                onChange={(e) => setProductData({...productData, category: e.target.value})}
                className="bg-gray-900 border border-gray-700 rounded-xl px-4 py-3 text-white text-sm"
              >
                <option value="">Catégorie</option>
                <option value="Sac à main">Sac à main</option>
                <option value="Chaussures">Chaussures</option>
                <option value="Vêtements">Vêtements</option>
                <option value="Accessoires">Accessoires</option>
              </select>
              <select
                value={productData.condition}
                onChange={(e) => setProductData({...productData, condition: e.target.value})}
                className="bg-gray-900 border border-gray-700 rounded-xl px-4 py-3 text-white text-sm"
              >
                <option value="">État</option>
                <option value="Neuf">Neuf</option>
                <option value="Excellent">Excellent</option>
                <option value="Très bon">Très bon</option>
                <option value="Bon">Bon</option>
              </select>
            </div>

            <input
              type="number"
              placeholder="Prix de vente (€)"
              value={productData.price}
              onChange={(e) => setProductData({...productData, price: e.target.value})}
              className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-3 text-white placeholder-gray-400 text-sm"
            />

            <textarea
              placeholder="Description détaillée du produit..."
              value={productData.description}
              onChange={(e) => setProductData({...productData, description: e.target.value})}
              className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-3 text-white placeholder-gray-400 h-32 text-sm"
            />

            <div className="border-2 border-dashed border-gray-600 rounded-xl p-6 text-center">
              <Upload className="w-8 h-8 text-gray-400 mx-auto mb-3" />
              <p className="text-gray-400 text-sm">Ajouter photos (optionnel)</p>
            </div>

            <button
              onClick={generateSheet}
              disabled={isGenerating || !productData.name || !productData.brand}
              className="w-full bg-gradient-to-r from-blue-500 to-purple-600 text-white px-6 py-4 rounded-xl font-bold hover:opacity-90 disabled:opacity-50 flex items-center justify-center"
            >
              {isGenerating ? (
                <>
                  <Loader className="w-5 h-5 animate-spin mr-2" />
                  Génération en cours...
                </>
              ) : (
                <>
                  <FileText className="w-5 h-5 mr-2" />
                  Générer la fiche
                </>
              )}
            </button>
          </div>
        </div>

        {/* Résultat généré */}
        <div className="bg-black/60 backdrop-blur-sm rounded-xl border border-purple-500/30 p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-purple-400 font-bold text-lg">📄 Fiche Générée</h3>
            {generatedSheet && (
              <div className="flex space-x-2">
                <button className="p-2 bg-gray-700 rounded-lg hover:bg-gray-600 transition-colors">
                  <Copy className="w-4 h-4 text-gray-300" />
                </button>
                <button className="p-2 bg-gray-700 rounded-lg hover:bg-gray-600 transition-colors">
                  <Download className="w-4 h-4 text-gray-300" />
                </button>
              </div>
            )}
          </div>
          
          {generatedSheet ? (
            <div className="bg-gray-900 rounded-xl p-4 border border-gray-700">
              <pre className="text-green-400 whitespace-pre-wrap text-sm leading-relaxed font-mono">
                {generatedSheet}
              </pre>
            </div>
          ) : (
            <div className="bg-gray-900 rounded-xl p-8 border border-gray-700 text-center">
              <FileText className="w-12 h-12 text-gray-500 mx-auto mb-4" />
              <p className="text-gray-400 text-sm">
                Remplissez les informations pour générer la fiche produit
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default FicheProduit;
